// tslint:disable
export const histories = [
  {
    details:
      'Indonesian comsat intended to replace the aging Telkom 1 at 108° E. First reflight of a Block 5-version booster.',
    event_date_unix: 1533619080,
    event_date_utc: '2018-08-07T05:18:00.000Z',
    id: '20',
    links: {
      article:
        'https://spaceflightnow.com/2018/08/07/indonesian-communications-satellite-deployed-in-orbit-by-spacex/',
      reddit:
        'https://www.reddit.com/r/spacex/comments/9539nr/rspacex_merah_putih_telkom4_official_launch/',
      wikipedia: 'https://en.wikipedia.org/wiki/Telkom_Indonesia',
    },
    title: 'First Block 5 Reflight',
    flight: {
      details:
        "SpaceX's fifteenth flight of 2018 launched the Merah Putih (also known as Telkom-4) geostationary communications satellite for Telkom Indonesia. It marked the first reuse of any Block 5 first stage; the booster B1046 had previously launched Bangabandhu-1. The stage was recovered and is expected to become the first Falcon 9 booster to fly three missions.",
      id: '67',
      is_tentative: false,
      launch_date_local: '2018-08-07T01:18:00-04:00',
      launch_date_unix: 1533619080,
      launch_date_utc: '2018-08-07T05:18:00.000Z',
      launch_site: {
        site_id: 'ccafs_slc_40',
        site_name_long:
          'Cape Canaveral Air Force Station Space Launch Complex 40',
        site_name: 'CCAFS SLC 40',
      },
      launch_success: true,
      launch_year: '2018',
      links: {
        article_link:
          'https://spaceflightnow.com/2018/08/07/indonesian-communications-satellite-deployed-in-orbit-by-spacex/',
        flickr_images: [
          'https://farm2.staticflickr.com/1798/43862495212_8fe1688c4b_o.jpg',
          'https://farm1.staticflickr.com/935/43006330655_f1623a3fa1_o.jpg',
          'https://farm1.staticflickr.com/938/28974313177_d16381ff5f_o.jpg',
          'https://farm2.staticflickr.com/1780/43006334045_fb7b4a8714_o.jpg',
          'https://farm1.staticflickr.com/929/28974335747_ffd87ff274_o.jpg',
          'https://farm1.staticflickr.com/930/30041972208_f735b9690b_o.jpg',
        ],
        mission_patch_small: 'https://images2.imgbox.com/a7/ec/sbwePzVD_o.png',
        mission_patch: 'https://images2.imgbox.com/a8/f5/ZgdsrbqW_o.png',
        presskit:
          'https://www.spacex.com/sites/spacex/files/merahputihpresskit.pdf',
        reddit_campaign:
          'https://www.reddit.com/r/spacex/comments/91gwfg/merah_putih_telkom4_launch_campaign_thread/',
        reddit_launch:
          'https://www.reddit.com/r/spacex/comments/9539nr/rspacex_merah_putih_telkom4_official_launch/',
        reddit_media:
          'https://www.reddit.com/r/spacex/comments/94zr0b/rspacex_merah_putih_media_thread_videos_images/',
        reddit_recovery: null,
        video_link: 'https://www.youtube.com/watch?v=FjfQNBYv2IY',
        wikipedia: 'https://en.wikipedia.org/wiki/Telkom_Indonesia',
      },
      mission_id: [],
      mission_name: 'Merah Putih',
      rocket: {
        fairings: {
          recovered: false,
          recovery_attempt: false,
          reused: false,
          ship: null,
        },
        first_stage: {
          cores: [
            {
              block: 5,
              core: {
                asds_attempts: 3,
                asds_landings: 3,
                block: 5,
                id: 'B1046',
                missions: [
                  { flight: 61, name: 'Bangabandhu-1' },
                  { flight: 67, name: 'Merah Putih' },
                  { flight: 71, name: 'SSO-A' },
                  { flight: 88, name: 'Crew Dragon In Flight Abort Test' },
                ],
                original_launch: '2018-05-11T20:14:00.000Z',
                reuse_count: 3,
                rtls_attempts: 0,
                rtls_landings: 0,
                status: 'lost',
                water_landing: false,
              },
              flight: 2,
              gridfins: true,
              land_success: true,
              landing_intent: true,
              landing_type: 'ASDS',
              landing_vehicle: 'OCISLY',
              legs: true,
              reused: true,
            },
          ],
        },
        rocket_name: 'Falcon 9',
        rocket_type: 'FT',
        rocket: { id: 'falcon9' },
        second_stage: { block: 5, payloads: [{ id: null }] },
      },
      static_fire_date_unix: 1533225180,
      static_fire_date_utc: '2018-08-02T15:53:00.000Z',
      telemetry: { flight_club: null },
      tentative_max_precision: 'hour',
      upcoming: false,
      ships: [{ id: 'HAWK' }, { id: 'OCISLY' }],
    },
  },
  {
    details:
      'The Bangabandhu Satellite-1 mission served as the first flight of Falcon 9 Block 5, the final substantial upgrade to SpaceX’s Falcon 9 launch vehicle. Falcon 9 Block 5 is designed to be capable of 10 or more flights with very limited refurbishment as SpaceX continues to strive for rapid reusability and extremely high reliability.',
    event_date_unix: 1526069640,
    event_date_utc: '2018-05-11T20:14:00Z',
    id: '19',
    links: {
      article:
        'https://spaceflightnow.com/2018/05/11/spacex-debuts-an-improved-human-rated-model-of-the-falcon-9-rocket/',
      reddit:
        'https://www.reddit.com/r/spacex/comments/8ioq3u/rspacex_bangabandhu1_official_launch_discussion/',
      wikipedia: 'https://en.wikipedia.org/wiki/Bangabandhu-1',
    },
    title: 'First Block 5 Launch',
    flight: {
      details: 'First launch of a Block V first stage.',
      id: '61',
      is_tentative: false,
      launch_date_local: '2018-05-11T16:14:00-04:00',
      launch_date_unix: 1526069640,
      launch_date_utc: '2018-05-11T20:14:00.000Z',
      launch_site: {
        site_id: 'ksc_lc_39a',
        site_name_long: 'Kennedy Space Center Historic Launch Complex 39A',
        site_name: 'KSC LC 39A',
      },
      launch_success: true,
      launch_year: '2018',
      links: {
        article_link:
          'https://spaceflightnow.com/2018/05/11/spacex-debuts-an-improved-human-rated-model-of-the-falcon-9-rocket/',
        flickr_images: [
          'https://farm1.staticflickr.com/903/28197547888_dd697d8147_o.jpg',
          'https://farm1.staticflickr.com/823/42025498712_8ec531950f_o.jpg',
          'https://farm1.staticflickr.com/975/28197546158_880e466fb6_o.jpg',
          'https://farm1.staticflickr.com/823/27200014957_940f3720bb_o.jpg',
          'https://farm1.staticflickr.com/945/42025498442_0b7b91d561_o.jpg',
          'https://farm1.staticflickr.com/967/42025498972_8720104d8a_o.jpg',
          'https://farm1.staticflickr.com/954/42025499162_8a0ef7feaa_o.jpg',
          'https://farm1.staticflickr.com/911/42025499722_47d3433d65_o.jpg',
        ],
        mission_patch_small: 'https://images2.imgbox.com/94/3a/eavaQRYD_o.png',
        mission_patch: 'https://images2.imgbox.com/df/cf/wlysigUT_o.png',
        presskit:
          'http://www.spacex.com/sites/spacex/files/bangabandhupresskit51118.pdf',
        reddit_campaign:
          'https://www.reddit.com/r/spacex/comments/8624iq/bangabandhu1_launch_campaign_thread/',
        reddit_launch:
          'https://www.reddit.com/r/spacex/comments/8ia091/rspacex_bangabandhu1_official_launch_discussion',
        reddit_media:
          'https://www.reddit.com/r/spacex/comments/8ia5bu/rspacex_bangabandhu1_media_thread_videos_images/',
        reddit_recovery:
          'https://www.reddit.com/r/spacex/comments/8j6moa/bangabandhu1_block_5_recovery_thread/',
        video_link: 'https://www.youtube.com/watch?v=rQEqKZ7CJlk',
        wikipedia: 'https://en.wikipedia.org/wiki/Bangabandhu-1',
      },
      mission_id: [],
      mission_name: 'Bangabandhu-1',
      rocket: {
        fairings: {
          recovered: false,
          recovery_attempt: false,
          reused: false,
          ship: null,
        },
        first_stage: {
          cores: [
            {
              block: 5,
              core: {
                asds_attempts: 3,
                asds_landings: 3,
                block: 5,
                id: 'B1046',
                missions: [
                  { flight: 61, name: 'Bangabandhu-1' },
                  { flight: 67, name: 'Merah Putih' },
                  { flight: 71, name: 'SSO-A' },
                  { flight: 88, name: 'Crew Dragon In Flight Abort Test' },
                ],
                original_launch: '2018-05-11T20:14:00.000Z',
                reuse_count: 3,
                rtls_attempts: 0,
                rtls_landings: 0,
                status: 'lost',
                water_landing: false,
              },
              flight: 1,
              gridfins: true,
              land_success: true,
              landing_intent: true,
              landing_type: 'ASDS',
              landing_vehicle: 'OCISLY',
              legs: true,
              reused: false,
            },
          ],
        },
        rocket_name: 'Falcon 9',
        rocket_type: 'FT',
        rocket: { id: 'falcon9' },
        second_stage: { block: 5, payloads: [{ id: null }] },
      },
      static_fire_date_unix: 1525476300,
      static_fire_date_utc: '2018-05-04T23:25:00.000Z',
      telemetry: { flight_club: 'https://www.flightclub.io/result?code=BNG1' },
      tentative_max_precision: 'hour',
      upcoming: false,
      ships: [
        { id: 'GOPURSUIT' },
        { id: 'GOQUEST' },
        { id: 'OCISLY' },
        { id: 'RACHEL' },
      ],
    },
  },
  {
    details:
      "Maiden flight of Falcon Heavy, using two recovered Falcon 9 cores as side boosters (from the Thaicom 8 and CRS-9 missions), as well as a modified Block 3 booster reinforced to endure the additional load from the two side boosters. The static fire test, held on January 24, was the first time 27 engines were tested together. The launch was a success, and the side boosters landed simultaneously at adjacent ground pads. Drone ship landing of the central core failed due to TEA–TEB chemical igniter running out, preventing two of its engines from restarting; the landing failure caused damage to the nearby drone ship. Final burn to heliocentric Mars–Earth orbit was performed after the second stage and payload cruised for 6 hours through the Van Allen belts. Later, Elon Musk tweeted that the third burn was successful, and JPL's HORIZONS system showed the second stage and payload in an orbit with an aphelion of 1.67 AU. The live webcast proved immensely popular, as it became the second most watched livestream ever on YouTube, reaching over 2.3 million concurrent views.",
    event_date_unix: 1517949900,
    event_date_utc: '2018-02-06T20:45:00Z',
    id: '18',
    links: {
      article:
        'https://spaceflightnow.com/2018/02/07/spacex-debuts-worlds-most-powerful-rocket-sends-tesla-toward-the-asteroid-belt/',
      reddit:
        'https://www.reddit.com/r/spacex/comments/7vg63x/rspacex_falcon_heavy_test_flight_official_launch/',
      wikipedia: 'https://en.wikipedia.org/wiki/Falcon_Heavy_test_flight',
    },
    title: 'Falcon Heavy Test Flight',
    flight: {
      details:
        'The launch was a success, and the side boosters landed simultaneously at adjacent ground pads. Drone ship landing of the central core failed. Final burn to heliocentric mars-earth orbit was successful after the second stage and payload passed through the Van Allen belts.',
      id: '55',
      is_tentative: false,
      launch_date_local: '2018-02-06T15:45:00-05:00',
      launch_date_unix: 1517949900,
      launch_date_utc: '2018-02-06T20:45:00.000Z',
      launch_site: {
        site_id: 'ksc_lc_39a',
        site_name_long: 'Kennedy Space Center Historic Launch Complex 39A',
        site_name: 'KSC LC 39A',
      },
      launch_success: true,
      launch_year: '2018',
      links: {
        article_link:
          'https://spaceflightnow.com/2018/02/07/spacex-debuts-worlds-most-powerful-rocket-sends-tesla-toward-the-asteroid-belt/',
        flickr_images: [
          'https://farm5.staticflickr.com/4745/40110304192_b0165b7785_o.jpg',
          'https://farm5.staticflickr.com/4676/40110297852_6173e5cae6_o.jpg',
          'https://farm5.staticflickr.com/4615/40143096241_0324643b5e_o.jpg',
          'https://farm5.staticflickr.com/4702/40110298232_4e9c412936_o.jpg',
          'https://farm5.staticflickr.com/4610/39337245575_41d760caef_o.jpg',
          'https://farm5.staticflickr.com/4654/25254688767_59603ff06c_o.jpg',
          'https://farm5.staticflickr.com/4627/40126462801_d54b4f00be_o.jpg',
          'https://farm5.staticflickr.com/4760/40126462231_cdf00ef431_o.jpg',
          'https://farm5.staticflickr.com/4655/40202121122_5d29cfe2ac_o.jpg',
          'https://farm5.staticflickr.com/4631/39337245145_5f5630a66a_o.jpg',
          'https://farm5.staticflickr.com/4650/40126461851_14b93ec9d7_o.jpg',
          'https://farm5.staticflickr.com/4711/40126461411_b1ed283d45_o.jpg',
          'https://farm5.staticflickr.com/4696/40126460511_7b5cc64871_o.jpg',
          'https://farm5.staticflickr.com/4589/38583831555_9ae89f5c10_o.jpg',
          'https://farm5.staticflickr.com/4682/38583829815_e01509d1a7_o.jpg',
          'https://farm5.staticflickr.com/4731/39225582801_80594d5d91_o.jpg',
          'https://farm5.staticflickr.com/4641/39225582421_7aa0c65851_o.jpg',
          'https://farm5.staticflickr.com/4643/27449864329_d2424bc280_o.jpg',
          'https://farm5.staticflickr.com/4681/39225582171_137a4c75e7_o.jpg',
          'https://farm5.staticflickr.com/4644/39225582351_ac6aba2533_o.jpg',
          'https://farm5.staticflickr.com/4587/27449863849_709e135a98_o.jpg',
        ],
        mission_patch_small: 'https://images2.imgbox.com/22/5f/jAAULKc3_o.png',
        mission_patch: 'https://images2.imgbox.com/33/1a/ujrnfkna_o.png',
        presskit:
          'http://www.spacex.com/sites/spacex/files/falconheavypresskit_v1.pdf',
        reddit_campaign:
          'https://www.reddit.com/r/spacex/comments/7hjp03/falcon_heavy_demo_launch_campaign_thread/',
        reddit_launch:
          'https://www.reddit.com/r/spacex/comments/7vg63x/rspacex_falcon_heavy_test_flight_official_launch/',
        reddit_media:
          'https://www.reddit.com/r/spacex/comments/7vimtm/rspacex_falcon_heavy_test_flight_media_thread/',
        reddit_recovery: null,
        video_link: 'https://www.youtube.com/watch?v=wbSwFU6tY1c',
        wikipedia: 'https://en.wikipedia.org/wiki/Elon_Musk%27s_Tesla_Roadster',
      },
      mission_id: [],
      mission_name: 'Falcon Heavy Test Flight',
      rocket: {
        fairings: {
          recovered: false,
          recovery_attempt: false,
          reused: false,
          ship: null,
        },
        first_stage: {
          cores: [
            {
              block: 3,
              core: {
                asds_attempts: 1,
                asds_landings: 0,
                block: 3,
                id: 'B1033',
                missions: [{ flight: 55, name: 'Falcon Heavy Test Flight' }],
                original_launch: '2018-02-06T20:45:00.000Z',
                reuse_count: 0,
                rtls_attempts: 0,
                rtls_landings: 0,
                status: 'lost',
                water_landing: false,
              },
              flight: 1,
              gridfins: true,
              land_success: false,
              landing_intent: true,
              landing_type: 'ASDS',
              landing_vehicle: 'OCISLY',
              legs: true,
              reused: false,
            },
            {
              block: 2,
              core: {
                asds_attempts: 0,
                asds_landings: 0,
                block: 2,
                id: 'B1025',
                missions: [
                  { flight: 32, name: 'CRS-9' },
                  { flight: 55, name: 'Falcon Heavy Test Flight' },
                ],
                original_launch: '2016-07-18T04:45:00.000Z',
                reuse_count: 1,
                rtls_attempts: 2,
                rtls_landings: 2,
                status: 'inactive',
                water_landing: false,
              },
              flight: 2,
              gridfins: true,
              land_success: true,
              landing_intent: true,
              landing_type: 'RTLS',
              landing_vehicle: 'LZ-2',
              legs: true,
              reused: true,
            },
            {
              block: 2,
              core: {
                asds_attempts: 1,
                asds_landings: 1,
                block: 2,
                id: 'B1023',
                missions: [
                  { flight: 30, name: 'Thaicom 8' },
                  { flight: 55, name: 'Falcon Heavy Test Flight' },
                ],
                original_launch: '2016-05-27T21:39:00.000Z',
                reuse_count: 1,
                rtls_attempts: 1,
                rtls_landings: 1,
                status: 'inactive',
                water_landing: false,
              },
              flight: 2,
              gridfins: true,
              land_success: true,
              landing_intent: true,
              landing_type: 'RTLS',
              landing_vehicle: 'LZ-1',
              legs: true,
              reused: true,
            },
          ],
        },
        rocket_name: 'Falcon Heavy',
        rocket_type: 'FT',
        rocket: { id: 'falconheavy' },
        second_stage: { block: 3, payloads: [{ id: null }] },
      },
      static_fire_date_unix: 1516815000,
      static_fire_date_utc: '2018-01-24T17:30:00.000Z',
      telemetry: { flight_club: 'https://www.flightclub.io/result?code=FHD1' },
      tentative_max_precision: 'hour',
      upcoming: false,
      ships: [{ id: 'GOSEARCHER' }, { id: 'HAWK' }, { id: 'OCISLY' }],
    },
  },
  {
    details:
      'This Dragon resupply mission represented the first reflight of a commercial spacecraft to and from the International Space Station.',
    event_date_unix: 1496524020,
    event_date_utc: '2017-06-03T21:07:00Z',
    id: '17',
    links: {
      article:
        'https://spaceflightnow.com/2017/06/03/reused-dragon-cargo-capsule-launched-on-journey-to-space-station/',
      reddit:
        'https://www.reddit.com/r/spacex/comments/6ektkt/welcome_to_the_rspacex_crs11_official_launch/',
      wikipedia: 'https://en.wikipedia.org/wiki/SpaceX_CRS-11',
    },
    title: 'First Dragon Reflight',
    flight: {
      details:
        'This mission delivered the Neutron Star Interior Composition Explorer (NICER) to the ISS, along with the MUSES Earth imaging platform and ROSA solar array. For the first time, this mission launched a refurbished Dragon capsule, serial number C106 which first flew in September 2014 on the CRS-4 mission. Originally scheduled to launch on June 1, but was scrubbed due to inclement weather.',
      id: '41',
      is_tentative: false,
      launch_date_local: '2017-06-03T17:07:00-04:00',
      launch_date_unix: 1496524020,
      launch_date_utc: '2017-06-03T21:07:00.000Z',
      launch_site: {
        site_id: 'ksc_lc_39a',
        site_name_long: 'Kennedy Space Center Historic Launch Complex 39A',
        site_name: 'KSC LC 39A',
      },
      launch_success: true,
      launch_year: '2017',
      links: {
        article_link:
          'https://spaceflightnow.com/2017/06/03/reused-dragon-cargo-capsule-launched-on-journey-to-space-station/',
        flickr_images: [
          'https://farm5.staticflickr.com/4210/34696326760_cee662ef1f_o.jpg',
          'https://farm5.staticflickr.com/4279/34239858024_64795724c9_o.jpg',
          'https://farm5.staticflickr.com/4250/35043398436_3ceaa0098a_o.jpg',
          'https://farm5.staticflickr.com/4223/34272083563_f52e5bfffe_o.jpg',
          'https://farm5.staticflickr.com/4219/34918571502_7cf66854f7_o.jpg',
          'https://farm5.staticflickr.com/4252/34918568732_4efe0885de_o.jpg',
          'https://farm5.staticflickr.com/4264/34272065153_cfd8899f3e_o.jpg',
          'https://farm5.staticflickr.com/4284/34948230531_e76b7560c9_o.jpg',
          'https://farm5.staticflickr.com/4280/35078830875_afbd41c675_o.jpg',
          'https://farm5.staticflickr.com/4280/34268361083_71fc70ff1a_o.jpg',
          'https://farm5.staticflickr.com/4199/35038651646_93d0339269_o.jpg',
          'https://farm5.staticflickr.com/4227/34223076793_4abe7e74d6_o.jpg',
        ],
        mission_patch_small: 'https://images2.imgbox.com/e8/33/RV791zv9_o.png',
        mission_patch: 'https://images2.imgbox.com/4b/88/4irzX449_o.png',
        presskit: 'http://www.spacex.com/sites/spacex/files/crs11presskit.pdf',
        reddit_campaign: 'https://www.reddit.com/r/spacex/comments/68ul58/',
        reddit_launch: 'https://www.reddit.com/r/spacex/comments/6ektkt/',
        reddit_media: 'https://www.reddit.com/r/spacex/comments/6emlzr/',
        reddit_recovery: null,
        video_link: 'https://www.youtube.com/watch?v=JuZBOUMsYws',
        wikipedia: 'https://en.wikipedia.org/wiki/SpaceX_CRS-11',
      },
      mission_id: ['EE86F74'],
      mission_name: 'CRS-11',
      rocket: {
        fairings: null,
        first_stage: {
          cores: [
            {
              block: 3,
              core: {
                asds_attempts: 0,
                asds_landings: 0,
                block: 3,
                id: 'B1035',
                missions: [
                  { flight: 41, name: 'CRS-11' },
                  { flight: 51, name: 'CRS-13' },
                ],
                original_launch: '2017-06-03T21:07:00.000Z',
                reuse_count: 1,
                rtls_attempts: 2,
                rtls_landings: 2,
                status: 'inactive',
                water_landing: false,
              },
              flight: 1,
              gridfins: true,
              land_success: true,
              landing_intent: true,
              landing_type: 'RTLS',
              landing_vehicle: 'LZ-1',
              legs: true,
              reused: false,
            },
          ],
        },
        rocket_name: 'Falcon 9',
        rocket_type: 'FT',
        rocket: { id: 'falcon9' },
        second_stage: { block: 3, payloads: [{ id: null }] },
      },
      static_fire_date_unix: 1495987200,
      static_fire_date_utc: '2017-05-28T16:00:00.000Z',
      telemetry: {
        flight_club: 'https://www.flightclub.io/results/?code=CR11',
      },
      tentative_max_precision: 'hour',
      upcoming: false,
      ships: [{ id: 'NRCQUEST' }],
    },
  },
  {
    details:
      "On March 30, 2017, SpaceX achieved the world's first reflight of an orbital class rocket. Following delivery of the payload, the Falcon 9 first stage returned to Earth for the second time.",
    event_date_unix: 1490912820,
    event_date_utc: '2017-03-30T22:27:00Z',
    id: '16',
    links: {
      article:
        'https://spaceflightnow.com/2017/03/31/spacex-flies-rocket-for-second-time-in-historic-test-of-cost-cutting-technology/',
      reddit:
        'https://www.reddit.com/r/spacex/comments/62aqi7/rspacex_ses10_official_launch_discussion_updates/',
      wikipedia: 'https://en.wikipedia.org/wiki/SES-10',
    },
    title: 'First Reflight',
    flight: {
      details:
        'First payload to fly on a reused first stage, B1021, previously launched with CRS-8, which also landed a second time. In what is also a first, the payload fairing remained intact after a successful splashdown achieved with thrusters and a steerable parachute.',
      id: '38',
      is_tentative: false,
      launch_date_local: '2017-03-30T18:27:00-04:00',
      launch_date_unix: 1490912820,
      launch_date_utc: '2017-03-30T22:27:00.000Z',
      launch_site: {
        site_id: 'ksc_lc_39a',
        site_name_long: 'Kennedy Space Center Historic Launch Complex 39A',
        site_name: 'KSC LC 39A',
      },
      launch_success: true,
      launch_year: '2017',
      links: {
        article_link:
          'https://spaceflightnow.com/2017/03/31/spacex-flies-rocket-for-second-time-in-historic-test-of-cost-cutting-technology/',
        flickr_images: [
          'https://farm1.staticflickr.com/601/33026465643_462ef7a2cb_o.jpg',
          'https://farm3.staticflickr.com/2850/32996438264_b79ca3664b_o.jpg',
          'https://farm4.staticflickr.com/3956/32996437434_4dab1ae8e3_o.jpg',
          'https://farm4.staticflickr.com/3831/32996435084_6c5662caca_o.jpg',
          'https://farm4.staticflickr.com/3775/32915200224_b6ecfabd7e_o.jpg',
          'https://farm4.staticflickr.com/3886/32915199874_b826eac153_o.jpg',
          'https://farm3.staticflickr.com/2842/32915199514_6c44178e87_o.jpg',
          'https://farm4.staticflickr.com/3771/32915198904_2df85aed05_o.jpg',
          'https://farm4.staticflickr.com/3668/32915198334_d2fa2f16ab_o.jpg',
          'https://farm4.staticflickr.com/3955/32915197674_24d6e27cf5_o.jpg',
          'https://farm4.staticflickr.com/3830/33616913981_f04b6e2351_o.jpg',
          'https://farm4.staticflickr.com/3819/33616913111_e699b48d66_o.jpg',
          'https://farm4.staticflickr.com/3835/33361035860_c57ed61239_o.jpg',
          'https://farm4.staticflickr.com/3783/33361035200_bfb797d38f_o.jpg',
          'https://farm4.staticflickr.com/3698/33611796351_54d5a6d65a_o.jpg',
          'https://farm3.staticflickr.com/2857/33611795531_82cc2d8789_o.jpg',
        ],
        mission_patch_small: 'https://images2.imgbox.com/5b/10/dfj7yRG3_o.png',
        mission_patch: 'https://images2.imgbox.com/d1/f6/9q2edz2p_o.png',
        presskit:
          'http://www.spacex.com/sites/spacex/files/finalses10presskit.pdf',
        reddit_campaign:
          'https://www.reddit.com/r/spacex/comments/5sjrzj/ses10_launch_campaign_thread/',
        reddit_launch:
          'https://www.reddit.com/r/spacex/comments/62aqi7/rspacex_ses10_official_launch_discussion_updates/',
        reddit_media:
          'https://www.reddit.com/r/spacex/comments/62aqad/rspacex_ses10_media_thread_videos_images_gifs/',
        reddit_recovery:
          'https://www.reddit.com/r/spacex/comments/634gmr/b1021ses10_recovery_thread/',
        video_link: 'https://www.youtube.com/watch?v=xsZSXav4wI8',
        wikipedia: 'https://en.wikipedia.org/wiki/SES-10',
      },
      mission_id: ['6C42550'],
      mission_name: 'SES-10',
      rocket: {
        fairings: {
          recovered: false,
          recovery_attempt: false,
          reused: false,
          ship: null,
        },
        first_stage: {
          cores: [
            {
              block: 2,
              core: {
                asds_attempts: 2,
                asds_landings: 2,
                block: 2,
                id: 'B1021',
                missions: [
                  { flight: 28, name: 'CRS-8' },
                  { flight: 38, name: 'SES-10' },
                ],
                original_launch: '2016-04-08T20:43:00.000Z',
                reuse_count: 1,
                rtls_attempts: 0,
                rtls_landings: 0,
                status: 'inactive',
                water_landing: false,
              },
              flight: 2,
              gridfins: true,
              land_success: true,
              landing_intent: true,
              landing_type: 'ASDS',
              landing_vehicle: 'OCISLY',
              legs: true,
              reused: true,
            },
          ],
        },
        rocket_name: 'Falcon 9',
        rocket_type: 'FT',
        rocket: { id: 'falcon9' },
        second_stage: { block: 2, payloads: [{ id: null }] },
      },
      static_fire_date_unix: 1490637600,
      static_fire_date_utc: '2017-03-27T18:00:00.000Z',
      telemetry: {
        flight_club: 'https://www.flightclub.io/results/?code=SS10',
      },
      tentative_max_precision: 'hour',
      upcoming: false,
      ships: [
        { id: 'ELSBETH3' },
        { id: 'GOQUEST' },
        { id: 'GOSEARCHER' },
        { id: 'OCISLY' },
      ],
    },
  },
  {
    details:
      'On April 8, 2016, the Falcon 9 rocket launched the Dragon spacecraft to the International Space Station, and the first stage returned and landed on the Of Course I Still Love You droneship.',
    event_date_unix: 1460148180,
    event_date_utc: '2016-04-08T20:43:00Z',
    id: '15',
    links: {
      article:
        'https://spaceflightnow.com/2016/04/08/spacex-lands-rocket-on-floating-platform-after-station-resupply-launch/',
      reddit:
        'https://www.reddit.com/r/spacex/comments/4dtoly/rspacex_spacex_crs8_official_launch_discussion/',
      wikipedia: 'https://en.wikipedia.org/wiki/SpaceX_CRS-8',
    },
    title: 'Droneship Landing',
    flight: {
      details:
        "Dragon carried over 1500 kg of supplies and delivered (stowed in its trunk) the inflatable Bigelow Expandable Activity Module (BEAM) to the ISS for two years of in-orbit tests. The rocket's first stage landed smoothly on SpaceX's autonomous spaceport drone ship 9 minutes after liftoff, making this the first ever successful landing of a rocket booster on a ship at sea as part of an orbital launch. The first stage B1021 was later also the first orbital booster to be used again, when launching SES-10 on March 30, 2017.",
      id: '28',
      is_tentative: false,
      launch_date_local: '2016-04-08T16:43:00-04:00',
      launch_date_unix: 1460148180,
      launch_date_utc: '2016-04-08T20:43:00.000Z',
      launch_site: {
        site_id: 'ccafs_slc_40',
        site_name_long:
          'Cape Canaveral Air Force Station Space Launch Complex 40',
        site_name: 'CCAFS SLC 40',
      },
      launch_success: true,
      launch_year: '2016',
      links: {
        article_link:
          'https://spaceflightnow.com/2016/04/08/spacex-lands-rocket-on-floating-platform-after-station-resupply-launch/',
        flickr_images: [
          'https://farm2.staticflickr.com/1633/25788014884_6a3f9ae183_o.jpg',
          'https://farm2.staticflickr.com/1650/26300505022_8b8b9035e8_o.jpg',
          'https://farm2.staticflickr.com/1486/25787998624_3ca213be1e_o.jpg',
          'https://farm2.staticflickr.com/1450/26326628031_e1b08ec0b3_o.jpg',
          'https://farm2.staticflickr.com/1670/26239020092_05e5e4c538_o.jpg',
          'https://farm2.staticflickr.com/1709/26305479266_76b4d01caf_o.jpg',
          'https://farm2.staticflickr.com/1645/26239017922_28c7ac50e0_o.jpg',
          'https://farm2.staticflickr.com/1559/26288402056_6c5997ce66_o.jpg',
          'https://farm2.staticflickr.com/1449/25709481274_60f8c77358_o.jpg',
          'https://farm2.staticflickr.com/1671/26217360302_b66c3e384e_o.jpg',
          'https://farm2.staticflickr.com/1704/26283822056_838c1103b9_o.jpg',
          'https://farm2.staticflickr.com/1508/26217345472_118767c608_o.jpg',
          'https://farm2.staticflickr.com/1495/25916886442_821a152917_o.jpg',
        ],
        mission_patch_small: 'https://images2.imgbox.com/49/2a/gkSR50yc_o.png',
        mission_patch: 'https://images2.imgbox.com/1b/f0/tyNDMK5j_o.png',
        presskit:
          'http://www.spacex.com/sites/spacex/files/spacex_crs8_press_kit.pdf',
        reddit_campaign: null,
        reddit_launch: 'https://www.reddit.com/r/spacex/comments/4dtoly',
        reddit_media: 'https://www.reddit.com/r/spacex/comments/4dtpxn/',
        reddit_recovery: 'https://www.reddit.com/r/spacex/comments/4ee2zy',
        video_link: 'https://www.youtube.com/watch?v=7pUAydjne5M',
        wikipedia: 'https://en.wikipedia.org/wiki/SpaceX_CRS-8',
      },
      mission_id: ['EE86F74'],
      mission_name: 'CRS-8',
      rocket: {
        fairings: null,
        first_stage: {
          cores: [
            {
              block: 2,
              core: {
                asds_attempts: 2,
                asds_landings: 2,
                block: 2,
                id: 'B1021',
                missions: [
                  { flight: 28, name: 'CRS-8' },
                  { flight: 38, name: 'SES-10' },
                ],
                original_launch: '2016-04-08T20:43:00.000Z',
                reuse_count: 1,
                rtls_attempts: 0,
                rtls_landings: 0,
                status: 'inactive',
                water_landing: false,
              },
              flight: 1,
              gridfins: true,
              land_success: true,
              landing_intent: true,
              landing_type: 'ASDS',
              landing_vehicle: 'OCISLY',
              legs: true,
              reused: false,
            },
          ],
        },
        rocket_name: 'Falcon 9',
        rocket_type: 'FT',
        rocket: { id: 'falcon9' },
        second_stage: { block: 2, payloads: [{ id: null }] },
      },
      static_fire_date_unix: 1459814400,
      static_fire_date_utc: '2016-04-05T00:00:00.000Z',
      telemetry: {
        flight_club: 'https://www.flightclub.io/results/?code=CRS8',
      },
      tentative_max_precision: 'hour',
      upcoming: false,
      ships: [
        { id: 'ELSBETH3' },
        { id: 'GOQUEST' },
        { id: 'GOSEARCHER' },
        { id: 'NRCQUEST' },
        { id: 'OCISLY' },
      ],
    },
  },
  {
    details:
      'On December 21, 2015, the Falcon 9 rocket delivered 11 communications satellites to orbit, and the first stage returned and landed at Landing Zone 1 -– the first-ever orbital class rocket landing.',
    event_date_unix: 1450747740,
    event_date_utc: '2015-12-22T01:29:00Z',
    id: '14',
    links: {
      article:
        'https://spaceflightnow.com/2015/12/22/round-trip-rocket-flight-gives-spacex-a-trifecta-of-successes/',
      reddit:
        'https://www.reddit.com/r/spacex/comments/3xgxh5/rspacex_orbcomm_og2_launch_2_official_launch/',
      wikipedia: 'https://en.wikipedia.org/wiki/Falcon_9_flight_20',
    },
    title: 'First Land Landing',
    flight: {
      details:
        'Total payload mass was 2,034 kg (4,484 lb) : 11 satellites weighing 172 kg each, plus a 142-kg mass simulator. This was the first launch of the upgraded v1.1 variant (later called Falcon 9 Full Thrust), with a 30 percent power increase. Orbcomm had originally agreed to be the third flight of the enhanced-thrust rocket, but the change to the maiden flight position was announced in October 2015. SpaceX received a permit from the FAA to land the booster on solid ground at Cape Canaveral, and succeeded.',
      id: '25',
      is_tentative: false,
      launch_date_local: '2015-12-22T21:29:00-04:00',
      launch_date_unix: 1450747740,
      launch_date_utc: '2015-12-22T01:29:00.000Z',
      launch_site: {
        site_id: 'ccafs_slc_40',
        site_name_long:
          'Cape Canaveral Air Force Station Space Launch Complex 40',
        site_name: 'CCAFS SLC 40',
      },
      launch_success: true,
      launch_year: '2015',
      links: {
        article_link:
          'https://spaceflightnow.com/2015/12/22/round-trip-rocket-flight-gives-spacex-a-trifecta-of-successes/',
        flickr_images: [
          'https://farm2.staticflickr.com/1648/23827554109_837b21739e_o.jpg',
          'https://farm1.staticflickr.com/597/23802553412_d41e4dcc64_o.jpg',
          'https://farm6.staticflickr.com/5806/23802550622_9ff8c90098_o.jpg',
          'https://farm1.staticflickr.com/571/23604164970_2a1a2366e4_o.jpg',
          'https://farm6.staticflickr.com/5773/23271687254_5e64d726ba_o.jpg',
          'https://farm6.staticflickr.com/5766/23526044959_5bfe74bc88_o.jpg',
          'https://farm6.staticflickr.com/5723/23785609832_83038751d1_o.jpg',
          'https://farm1.staticflickr.com/715/23833499336_d3fde6a25a_o.jpg',
        ],
        mission_patch_small: 'https://images2.imgbox.com/89/e8/5eeThzqZ_o.png',
        mission_patch: 'https://images2.imgbox.com/65/a5/8iNE9T6Y_o.png',
        presskit:
          'http://www.spacex.com/sites/spacex/files/spacex_orbcomm_press_kit_final2.pdf',
        reddit_campaign: null,
        reddit_launch: 'https://www.reddit.com/r/spacex/comments/3xgxh5',
        reddit_media: 'https://www.reddit.com/r/spacex/comments/3xm83h/',
        reddit_recovery: null,
        video_link: 'https://www.youtube.com/watch?v=O5bTbVbe4e4',
        wikipedia: 'https://en.wikipedia.org/wiki/Falcon_9_flight_20',
      },
      mission_id: ['CE91D46'],
      mission_name: 'OG-2 Mission 2',
      rocket: {
        fairings: {
          recovered: false,
          recovery_attempt: false,
          reused: false,
          ship: null,
        },
        first_stage: {
          cores: [
            {
              block: 1,
              core: {
                asds_attempts: 0,
                asds_landings: 0,
                block: 1,
                id: 'B1019',
                missions: [{ flight: 25, name: 'OG-2 Mission 2' }],
                original_launch: '2015-12-22T01:29:00.000Z',
                reuse_count: 0,
                rtls_attempts: 1,
                rtls_landings: 1,
                status: 'inactive',
                water_landing: false,
              },
              flight: 1,
              gridfins: true,
              land_success: true,
              landing_intent: true,
              landing_type: 'RTLS',
              landing_vehicle: 'LZ-1',
              legs: true,
              reused: false,
            },
          ],
        },
        rocket_name: 'Falcon 9',
        rocket_type: 'FT',
        rocket: { id: 'falcon9' },
        second_stage: { block: 1, payloads: [{ id: null }] },
      },
      static_fire_date_unix: 1450483740,
      static_fire_date_utc: '2015-12-19T00:09:00.000Z',
      telemetry: {
        flight_club: 'https://www.flightclub.io/results/?code=OG22',
      },
      tentative_max_precision: 'hour',
      upcoming: false,
      ships: [],
    },
  },
  {
    details:
      'Crew Dragon tests launch abort system, which can provide astronauts with escape capability all the way to orbit.',
    event_date_unix: 1430917200,
    event_date_utc: '2015-05-06T13:00:00Z',
    id: '13',
    links: {
      article:
        'https://spaceflightnow.com/2015/04/21/dragon-pad-abort-test-set-for-early-may/',
      reddit:
        'https://www.reddit.com/r/spacex/comments/3527zv/official_video_pad_abort_test_2015/',
      wikipedia: 'https://en.wikipedia.org/wiki/Pad_abort_test',
    },
    title: 'Pad Abort Test',
    flight: null,
  },
  {
    details:
      'SpaceX begins series of first stage landing attempts on an autonomous spaceport drone ship.',
    event_date_unix: 1420883220,
    event_date_utc: '2015-01-10T09:47:00Z',
    id: '12',
    links: {
      article:
        'https://spaceflightnow.com/2015/01/10/dragon-successfully-launched-rocket-recovery-demo-crash-lands/',
      reddit: 'http://www.reddit.com/r/spacex/comments/2rrdha',
      wikipedia: 'https://en.wikipedia.org/wiki/SpaceX_CRS-5',
    },
    title: 'Drone Ship Landings',
    flight: {
      details:
        "Following second stage separation, SpaceX performed a test flight which attempted to return the first stage of the Falcon 9 through the atmosphere and land it on an approximately 90-by-50-meter (300 ft x 160 ft) floating platform-called the autonomous spaceport drone ship. Many of the test objectives were achieved, including precision control of the rocket's descent to land on the platform at a specific point in the Atlantic ocean, and a large amount of test data was obtained from the first use of grid fin control surfaces used for more precise reentry positioning. The grid fin control system ran out of hydraulic fluid a minute before landing and the landing itself resulted in a crash.",
      id: '19',
      is_tentative: false,
      launch_date_local: '2015-01-10T05:47:00-04:00',
      launch_date_unix: 1420883220,
      launch_date_utc: '2015-01-10T09:47:00.000Z',
      launch_site: {
        site_id: 'ccafs_slc_40',
        site_name_long:
          'Cape Canaveral Air Force Station Space Launch Complex 40',
        site_name: 'CCAFS SLC 40',
      },
      launch_success: true,
      launch_year: '2015',
      links: {
        article_link:
          'https://spaceflightnow.com/2015/01/10/dragon-successfully-launched-rocket-recovery-demo-crash-lands/',
        flickr_images: [
          'https://farm9.staticflickr.com/8666/16511391418_bb5cdbbd71_o.jpg',
          'https://farm9.staticflickr.com/8612/16848173281_035bdc6009_o.jpg',
          'https://farm9.staticflickr.com/8571/16699496805_bf39747618_o.jpg',
          'https://farm9.staticflickr.com/8650/16699496705_187e4e53fd_o.jpg',
          'https://farm9.staticflickr.com/8663/16077174554_370937efbe_o.jpg',
          'https://farm9.staticflickr.com/8638/16512101410_83763eb9ea_o.jpg',
          'https://farm9.staticflickr.com/8653/16077173984_17885d4bea_o.jpg',
          'https://farm8.staticflickr.com/7635/16848159582_40c0f9d25f_o.jpg',
        ],
        mission_patch_small: 'https://images2.imgbox.com/25/b6/RhNppyL3_o.png',
        mission_patch: 'https://images2.imgbox.com/fe/5a/WyQS4MXa_o.png',
        presskit:
          'http://www.spacex.com/sites/spacex/files/spacex_nasa_crs-5_presskit.pdf',
        reddit_campaign: null,
        reddit_launch: 'http://www.reddit.com/r/spacex/comments/2rrdha',
        reddit_media: null,
        reddit_recovery: null,
        video_link: 'https://www.youtube.com/watch?v=p7x-SumbynI',
        wikipedia: 'https://en.wikipedia.org/wiki/SpaceX_CRS-5',
      },
      mission_id: ['EE86F74'],
      mission_name: 'CRS-5',
      rocket: {
        fairings: null,
        first_stage: {
          cores: [
            {
              block: 1,
              core: {
                asds_attempts: 1,
                asds_landings: 0,
                block: 1,
                id: 'B1012',
                missions: [{ flight: 19, name: 'CRS-5' }],
                original_launch: '2015-01-10T09:47:00.000Z',
                reuse_count: 0,
                rtls_attempts: 0,
                rtls_landings: 0,
                status: 'lost',
                water_landing: false,
              },
              flight: 1,
              gridfins: true,
              land_success: false,
              landing_intent: true,
              landing_type: 'ASDS',
              landing_vehicle: 'JRTI-1',
              legs: true,
              reused: false,
            },
          ],
        },
        rocket_name: 'Falcon 9',
        rocket_type: 'v1.1',
        rocket: { id: 'falcon9' },
        second_stage: { block: 1, payloads: [{ id: null }] },
      },
      static_fire_date_unix: 1529789400,
      static_fire_date_utc: '2018-06-23T21:30:00.000Z',
      telemetry: { flight_club: null },
      tentative_max_precision: 'hour',
      upcoming: false,
      ships: [
        { id: 'ELSBETH3' },
        { id: 'GOQUEST' },
        { id: 'GOSEARCHER' },
        { id: 'JRTI-1' },
        { id: 'NRCQUEST' },
      ],
    },
  },
  {
    details:
      'NASA awards $2.6 billion SpaceX contract to fly American astronauts.',
    event_date_unix: 1410829200,
    event_date_utc: '2014-09-16T01:00:00Z',
    id: '11',
    links: {
      article:
        'https://www.washingtonpost.com/news/the-switch/wp/2014/09/16/nasa-awards-space-contract-to-boeing-and-spacex/?utm_term=.d6388390d071',
      reddit: null,
      wikipedia: null,
    },
    title: 'SpaceX Awarded Commercial Crew Contract',
    flight: null,
  },
];
