export const upcomings = [
  {
    details: null,
    id: '122',
    is_tentative: true,
    launch_date_local: '2021-06-30T20:00:00-04:00',
    launch_date_unix: 1625097600,
    launch_date_utc: '2021-07-01T00:00:00.000Z',
    launch_site: {
      site_id: 'ccafs_slc_40',
      site_name_long:
        'Cape Canaveral Air Force Station Space Launch Complex 40',
      site_name: 'CCAFS SLC 40',
    },
    launch_success: null,
    launch_year: '2021',
    links: {
      article_link: null,
      flickr_images: [],
      mission_patch_small: null,
      mission_patch: null,
      presskit: null,
      reddit_campaign: null,
      reddit_launch: null,
      reddit_media: null,
      reddit_recovery: null,
      video_link: null,
      wikipedia: null,
    },
    mission_id: [],
    mission_name: 'GPS III SV05',
    rocket: {
      fairings: {
        recovered: null,
        recovery_attempt: null,
        reused: null,
        ship: null,
      },
      first_stage: {
        cores: [
          {
            block: 5,
            core: null,
            flight: null,
            gridfins: null,
            land_success: null,
            landing_intent: null,
            landing_type: null,
            landing_vehicle: null,
            legs: null,
            reused: false,
          },
        ],
      },
      rocket_name: 'Falcon 9',
      rocket_type: 'FT',
      rocket: { id: 'falcon9' },
      second_stage: { block: 5, payloads: [{ id: null }] },
    },
    static_fire_date_unix: null,
    static_fire_date_utc: null,
    telemetry: { flight_club: null },
    tentative_max_precision: 'month',
    upcoming: true,
    ships: [],
  },
  {
    details: null,
    id: '109',
    is_tentative: false,
    launch_date_local: '2020-11-10T11:31:00-08:00',
    launch_date_unix: 1605036660,
    launch_date_utc: '2020-11-10T19:31:00.000Z',
    launch_site: {
      site_id: 'vafb_slc_4e',
      site_name_long: 'Vandenberg Air Force Base Space Launch Complex 4E',
      site_name: 'VAFB SLC 4E',
    },
    launch_success: null,
    launch_year: '2020',
    links: {
      article_link: null,
      flickr_images: [],
      mission_patch_small: null,
      mission_patch: null,
      presskit: null,
      reddit_campaign: null,
      reddit_launch: null,
      reddit_media: null,
      reddit_recovery: null,
      video_link: null,
      wikipedia: null,
    },
    mission_id: [],
    mission_name: 'Sentinel-6 Michael Freilich',
    rocket: {
      fairings: {
        recovered: null,
        recovery_attempt: null,
        reused: null,
        ship: null,
      },
      first_stage: {
        cores: [
          {
            block: 5,
            core: null,
            flight: null,
            gridfins: null,
            land_success: null,
            landing_intent: null,
            landing_type: null,
            landing_vehicle: null,
            legs: null,
            reused: null,
          },
        ],
      },
      rocket_name: 'Falcon 9',
      rocket_type: 'FT',
      rocket: { id: 'falcon9' },
      second_stage: { block: 5, payloads: [{ id: null }] },
    },
    static_fire_date_unix: null,
    static_fire_date_utc: null,
    telemetry: { flight_club: null },
    tentative_max_precision: 'hour',
    upcoming: true,
    ships: [],
  },
  {
    details: null,
    id: '108',
    is_tentative: true,
    launch_date_local: '2020-10-31T20:00:00-04:00',
    launch_date_unix: 1604188800,
    launch_date_utc: '2020-11-01T00:00:00.000Z',
    launch_site: {
      site_id: 'ksc_lc_39a',
      site_name_long: 'Kennedy Space Center Historic Launch Complex 39A',
      site_name: 'KSC LC 39A',
    },
    launch_success: null,
    launch_year: '2020',
    links: {
      article_link: null,
      flickr_images: [],
      mission_patch_small: null,
      mission_patch: null,
      presskit: null,
      reddit_campaign: null,
      reddit_launch: null,
      reddit_media: null,
      reddit_recovery: null,
      video_link: null,
      wikipedia: null,
    },
    mission_id: [],
    mission_name: 'SXM-7',
    rocket: {
      fairings: {
        recovered: null,
        recovery_attempt: null,
        reused: null,
        ship: null,
      },
      first_stage: {
        cores: [
          {
            block: 5,
            core: null,
            flight: null,
            gridfins: null,
            land_success: null,
            landing_intent: null,
            landing_type: null,
            landing_vehicle: null,
            legs: null,
            reused: null,
          },
        ],
      },
      rocket_name: 'Falcon 9',
      rocket_type: 'FT',
      rocket: { id: 'falcon9' },
      second_stage: { block: 5, payloads: [{ id: null }] },
    },
    static_fire_date_unix: null,
    static_fire_date_utc: null,
    telemetry: { flight_club: null },
    tentative_max_precision: 'month',
    upcoming: true,
    ships: [],
  },
  {
    details: null,
    id: '110',
    is_tentative: true,
    launch_date_local: '2020-10-31T20:00:00-04:00',
    launch_date_unix: 1604188800,
    launch_date_utc: '2020-11-01T00:00:00.000Z',
    launch_site: {
      site_id: 'ksc_lc_39a',
      site_name_long: 'Kennedy Space Center Historic Launch Complex 39A',
      site_name: 'KSC LC 39A',
    },
    launch_success: null,
    launch_year: '2020',
    links: {
      article_link: null,
      flickr_images: [],
      mission_patch_small: null,
      mission_patch: null,
      presskit: null,
      reddit_campaign: null,
      reddit_launch: null,
      reddit_media: null,
      reddit_recovery: null,
      video_link: null,
      wikipedia: null,
    },
    mission_id: ['EE86F74'],
    mission_name: 'CRS-21',
    rocket: {
      fairings: null,
      first_stage: {
        cores: [
          {
            block: 5,
            core: null,
            flight: null,
            gridfins: null,
            land_success: null,
            landing_intent: null,
            landing_type: null,
            landing_vehicle: null,
            legs: null,
            reused: true,
          },
        ],
      },
      rocket_name: 'Falcon 9',
      rocket_type: 'FT',
      rocket: { id: 'falcon9' },
      second_stage: { block: 5, payloads: [{ id: null }] },
    },
    static_fire_date_unix: null,
    static_fire_date_utc: null,
    telemetry: { flight_club: null },
    tentative_max_precision: 'month',
    upcoming: true,
    ships: [],
  },
  {
    details: null,
    id: '111',
    is_tentative: true,
    launch_date_local: '2020-10-31T20:00:00-04:00',
    launch_date_unix: 1604188800,
    launch_date_utc: '2020-11-01T00:00:00.000Z',
    launch_site: {
      site_id: 'ccafs_slc_40',
      site_name_long:
        'Cape Canaveral Air Force Station Space Launch Complex 40',
      site_name: 'CCAFS SLC 40',
    },
    launch_success: null,
    launch_year: '2020',
    links: {
      article_link: null,
      flickr_images: [],
      mission_patch_small: null,
      mission_patch: null,
      presskit: null,
      reddit_campaign: null,
      reddit_launch: null,
      reddit_media: null,
      reddit_recovery: null,
      video_link: null,
      wikipedia: null,
    },
    mission_id: [],
    mission_name: 'Turksat 5A',
    rocket: {
      fairings: {
        recovered: null,
        recovery_attempt: null,
        reused: null,
        ship: null,
      },
      first_stage: {
        cores: [
          {
            block: 5,
            core: null,
            flight: null,
            gridfins: null,
            land_success: null,
            landing_intent: null,
            landing_type: null,
            landing_vehicle: null,
            legs: null,
            reused: true,
          },
        ],
      },
      rocket_name: 'Falcon 9',
      rocket_type: 'FT',
      rocket: { id: 'falcon9' },
      second_stage: { block: 5, payloads: [{ id: null }] },
    },
    static_fire_date_unix: null,
    static_fire_date_utc: null,
    telemetry: { flight_club: null },
    tentative_max_precision: 'month',
    upcoming: true,
    ships: [],
  },
  {
    details: null,
    id: '107',
    is_tentative: false,
    launch_date_local: '2020-10-23T05:47:00-04:00',
    launch_date_unix: 1603446420,
    launch_date_utc: '2020-10-23T09:47:00.000Z',
    launch_site: {
      site_id: 'ksc_lc_39a',
      site_name_long: 'Kennedy Space Center Historic Launch Complex 39A',
      site_name: 'KSC LC 39A',
    },
    launch_success: null,
    launch_year: '2020',
    links: {
      article_link: null,
      flickr_images: [],
      mission_patch_small: null,
      mission_patch: null,
      presskit: null,
      reddit_campaign: null,
      reddit_launch: null,
      reddit_media: null,
      reddit_recovery: null,
      video_link: null,
      wikipedia: null,
    },
    mission_id: ['EE86F74'],
    mission_name: 'Crew-1',
    rocket: {
      fairings: null,
      first_stage: {
        cores: [
          {
            block: 5,
            core: null,
            flight: null,
            gridfins: null,
            land_success: null,
            landing_intent: null,
            landing_type: null,
            landing_vehicle: null,
            legs: null,
            reused: false,
          },
        ],
      },
      rocket_name: 'Falcon 9',
      rocket_type: 'FT',
      rocket: { id: 'falcon9' },
      second_stage: { block: 5, payloads: [{ id: null }] },
    },
    static_fire_date_unix: null,
    static_fire_date_utc: null,
    telemetry: { flight_club: null },
    tentative_max_precision: 'hour',
    upcoming: true,
    ships: [],
  },
  {
    details:
      'This mission will launch the twelfth batch of operational Starlink satellites, which are expected to be version 1.0, from SLC-40, Cape Canaveral Air Force Station. It is the thirteenth Starlink launch overall. The satellites will be delivered to low Earth orbit and will spend a few weeks maneuvering to their operational altitude of 550 km. The booster for this mission is expected to land on an ASDS.',
    id: '104',
    is_tentative: false,
    launch_date_local: '2020-10-01T09:17:00-04:00',
    launch_date_unix: 1601558220,
    launch_date_utc: '2020-10-01T13:17:00.000Z',
    launch_site: {
      site_id: 'ksc_lc_39a',
      site_name_long: 'Kennedy Space Center Historic Launch Complex 39A',
      site_name: 'KSC LC 39A',
    },
    launch_success: null,
    launch_year: '2020',
    links: {
      article_link: null,
      flickr_images: [],
      mission_patch_small: 'https://images2.imgbox.com/9a/96/nLppz9HW_o.png',
      mission_patch: 'https://images2.imgbox.com/d2/3b/bQaWiil0_o.png',
      presskit: null,
      reddit_campaign:
        'https://www.reddit.com/r/spacex/comments/i63bst/starlink_general_discussion_and_deployment_thread/',
      reddit_launch:
        'https://www.reddit.com/r/spacex/comments/iu0vtg/rspacex_starlink12_official_launch_discussion/',
      reddit_media:
        'https://www.reddit.com/r/spacex/comments/iudifm/rspacex_starlink12_media_thread_photographer/',
      reddit_recovery: null,
      video_link: 'https://youtu.be/8O8Z2yPyTnc',
      wikipedia: 'https://en.wikipedia.org/wiki/Starlink',
    },
    mission_id: [],
    mission_name: 'Starlink-12 (v1.0)',
    rocket: {
      fairings: {
        recovered: null,
        recovery_attempt: true,
        reused: true,
        ship: 'GOMSCHIEF',
      },
      first_stage: {
        cores: [
          {
            block: 5,
            core: {
              asds_attempts: 2,
              asds_landings: 2,
              block: 5,
              id: 'B1058',
              missions: [
                { flight: 94, name: 'CCtCap Demo Mission 2' },
                { flight: 98, name: 'ANASIS-II' },
              ],
              original_launch: '2020-05-30T19:22:00.000Z',
              reuse_count: 1,
              rtls_attempts: 0,
              rtls_landings: 0,
              status: 'unknown',
              water_landing: false,
            },
            flight: 3,
            gridfins: true,
            land_success: null,
            landing_intent: true,
            landing_type: 'ASDS',
            landing_vehicle: 'JRTI',
            legs: true,
            reused: true,
          },
        ],
      },
      rocket_name: 'Falcon 9',
      rocket_type: 'FT',
      rocket: { id: 'falcon9' },
      second_stage: { block: 5, payloads: [{ id: null }] },
    },
    static_fire_date_unix: null,
    static_fire_date_utc: null,
    telemetry: { flight_club: null },
    tentative_max_precision: 'hour',
    upcoming: true,
    ships: [{ id: 'GOQUEST' }, null, { id: 'GOMSCHIEF' }],
  },
  {
    details:
      'This mission will launch the thirteenth batch of operational Starlink satellites, which are expected to be version 1.0, from LC-39A, Kennedy Space Center. It is the fourteenth Starlink launch overall. The satellites will be delivered to low Earth orbit and will spend a few weeks maneuvering to their operational altitude of 550 km. The booster for this mission is expected to land on an ASDS.',
    id: '105',
    is_tentative: true,
    launch_date_local: '2020-09-30T20:00:00-04:00',
    launch_date_unix: 1601510400,
    launch_date_utc: '2020-10-01T00:00:00.000Z',
    launch_site: {
      site_id: 'ccafs_slc_40',
      site_name_long:
        'Cape Canaveral Air Force Station Space Launch Complex 40',
      site_name: 'CCAFS SLC 40',
    },
    launch_success: null,
    launch_year: '2020',
    links: {
      article_link: null,
      flickr_images: [],
      mission_patch_small: 'https://images2.imgbox.com/9a/96/nLppz9HW_o.png',
      mission_patch: 'https://images2.imgbox.com/d2/3b/bQaWiil0_o.png',
      presskit: null,
      reddit_campaign: null,
      reddit_launch: null,
      reddit_media: null,
      reddit_recovery: null,
      video_link: null,
      wikipedia: null,
    },
    mission_id: [],
    mission_name: 'Starlink-13 (v1.0)',
    rocket: {
      fairings: {
        recovered: null,
        recovery_attempt: null,
        reused: null,
        ship: null,
      },
      first_stage: {
        cores: [
          {
            block: 5,
            core: null,
            flight: null,
            gridfins: null,
            land_success: null,
            landing_intent: null,
            landing_type: null,
            landing_vehicle: null,
            legs: null,
            reused: true,
          },
        ],
      },
      rocket_name: 'Falcon 9',
      rocket_type: 'FT',
      rocket: { id: 'falcon9' },
      second_stage: { block: 5, payloads: [{ id: null }] },
    },
    static_fire_date_unix: null,
    static_fire_date_utc: null,
    telemetry: { flight_club: null },
    tentative_max_precision: 'month',
    upcoming: true,
    ships: [],
  },
  {
    details: null,
    id: '106',
    is_tentative: true,
    launch_date_local: '2020-09-30T20:00:00-04:00',
    launch_date_unix: 1601510400,
    launch_date_utc: '2020-10-01T00:00:00.000Z',
    launch_site: {
      site_id: 'ccafs_slc_40',
      site_name_long:
        'Cape Canaveral Air Force Station Space Launch Complex 40',
      site_name: 'CCAFS SLC 40',
    },
    launch_success: null,
    launch_year: '2020',
    links: {
      article_link: null,
      flickr_images: [],
      mission_patch_small: 'https://images2.imgbox.com/9a/96/nLppz9HW_o.png',
      mission_patch: 'https://images2.imgbox.com/d2/3b/bQaWiil0_o.png',
      presskit: null,
      reddit_campaign: null,
      reddit_launch: null,
      reddit_media: null,
      reddit_recovery: null,
      video_link: null,
      wikipedia: null,
    },
    mission_id: [],
    mission_name: 'Starlink-14 (v1.0)',
    rocket: {
      fairings: {
        recovered: null,
        recovery_attempt: null,
        reused: null,
        ship: null,
      },
      first_stage: {
        cores: [
          {
            block: 5,
            core: null,
            flight: null,
            gridfins: null,
            land_success: null,
            landing_intent: null,
            landing_type: null,
            landing_vehicle: null,
            legs: null,
            reused: true,
          },
        ],
      },
      rocket_name: 'Falcon 9',
      rocket_type: 'FT',
      rocket: { id: 'falcon9' },
      second_stage: { block: 5, payloads: [{ id: null }] },
    },
    static_fire_date_unix: null,
    static_fire_date_utc: null,
    telemetry: { flight_club: null },
    tentative_max_precision: 'month',
    upcoming: true,
    ships: [],
  },
  {
    details:
      'SpaceX will launch GPS Block III Space Vehicle 04 from SLC-40, Cape Canaveral AFS aboard a Falcon 9. GPS III is owned and operated by the US Air Force and produced by Lockheed Martin. This will be the fourth GPS III satellite launched and the third launched by SpaceX. The satellite will be delivered into a MEO transfer orbit. The booster for this mission will land on an ASDS.',
    id: '103',
    is_tentative: false,
    launch_date_local: '2020-09-29T21:55:00-04:00',
    launch_date_unix: 1601430900,
    launch_date_utc: '2020-09-30T01:55:00.000Z',
    launch_site: {
      site_id: 'ccafs_slc_40',
      site_name_long:
        'Cape Canaveral Air Force Station Space Launch Complex 40',
      site_name: 'CCAFS SLC 40',
    },
    launch_success: null,
    launch_year: '2020',
    links: {
      article_link: null,
      flickr_images: [],
      mission_patch_small: null,
      mission_patch: null,
      presskit: null,
      reddit_campaign:
        'https://www.reddit.com/r/spacex/comments/io0swm/gps_iii_sv04_launch_campaign_thread/',
      reddit_launch: null,
      reddit_media: null,
      reddit_recovery: null,
      video_link: null,
      wikipedia: null,
    },
    mission_id: [],
    mission_name: 'GPS III SV04',
    rocket: {
      fairings: {
        recovered: null,
        recovery_attempt: null,
        reused: null,
        ship: null,
      },
      first_stage: {
        cores: [
          {
            block: 5,
            core: {
              asds_attempts: 0,
              asds_landings: 0,
              block: 5,
              id: 'B1062',
              missions: [],
              original_launch: null,
              reuse_count: 0,
              rtls_attempts: 0,
              rtls_landings: 0,
              status: null,
              water_landing: false,
            },
            flight: 1,
            gridfins: true,
            land_success: null,
            landing_intent: true,
            landing_type: 'ASDS',
            landing_vehicle: null,
            legs: true,
            reused: false,
          },
        ],
      },
      rocket_name: 'Falcon 9',
      rocket_type: 'FT',
      rocket: { id: 'falcon9' },
      second_stage: { block: 5, payloads: [{ id: null }] },
    },
    static_fire_date_unix: null,
    static_fire_date_utc: null,
    telemetry: { flight_club: null },
    tentative_max_precision: 'hour',
    upcoming: true,
    ships: [],
  },
];
